# Generated by Django 6.1 on 2026-08-21 17:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en_dispositivo', models.DateTimeField(default=django.utils.timezone.now)),
                ('sincronizado_en_nube', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Ejecución'), ('EN_PROGRESO', 'En Progreso'), ('DETENIDA', 'Detenida por Bloqueo'), ('FINALIZADA', 'Finalizada al 100%')], default='PENDIENTE', max_length=20)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0)),
                ('fecha_limite_proyectada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroDowntime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en_dispositivo', models.DateTimeField(default=django.utils.timezone.now)),
                ('sincronizado_en_nube', models.DateTimeField(auto_now_add=True)),
                ('causa_raiz', models.CharField(choices=[('FALLA_MECANICA', 'Falla Mecánica (Ej. Compresora)'), ('FALTA_MATERIAL', 'Falta de Material (Ej. Cemento/Agua)'), ('CLIMA_ADVERSO', 'Condición Climática (Ej. Tormenta Eléctrica)'), ('CORTE_ENERGIA', 'Corte de Energía Programado/Imprevisto'), ('OTROS', 'Otros (Requiere justificación)')], max_length=20)),
                ('detalle_tecnico', models.TextField()),
                ('duracion_horas_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_muertos', to='operaciones.tarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
