# Generated by Django 6.1 on 2026-08-21 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en_dispositivo', models.DateTimeField(default=django.utils.timezone.now)),
                ('sincronizado_en_nube', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('CASCO', 'Casco de Seguridad'), ('LAMPARA', 'Lámpara Minera'), ('CARGADOR', 'Cargador de Lámpara'), ('AUTORRESCATADOR', 'Autorescatador'), ('BOTAS', 'Botas de Seguridad'), ('ARNES', 'Arnés de Seguridad'), ('OTROS', 'Otro EPP')], max_length=20)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_reposicion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vida_util_meses', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['categoria', 'codigo_inventario'], name='operaciones_categor_fdaf9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en_dispositivo', models.DateTimeField(default=django.utils.timezone.now)),
                ('sincronizado_en_nube', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('turno_actual', models.CharField(choices=[('DIA', 'Guardia Día'), ('NOCHE', 'Guardia Noche')], default='DIA', max_length=10)),
                ('foto_perfil_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_ingreso_mina', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dni'], name='operaciones_dni_44cc64_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en_dispositivo', models.DateTimeField(default=django.utils.timezone.now)),
                ('sincronizado_en_nube', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ENTREGADO', 'Entregado - en posesión del operador'), ('DEVUELTO_OK', 'Devuelto en buen estado'), ('DEVUELTO_DANADO', 'Devuelto con daño (penalización parcial)'), ('PERDIDO', 'Perdido / no devuelto (penalización total)'), ('EN_REPARACION', 'En reparación')], default='ENTREGADO', max_length=20)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion_esperada', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('evidencia_entrega_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('evidencia_devolucion_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('monto_penalizacion_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('observaciones', models.TextField(blank=True)),
                ('valor_reposicion_congelado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='operaciones.itemepp')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_epp', to='operaciones.operador')),
            ],
            options={
                'indexes': [models.Index(fields=['operador', 'estado'], name='operaciones_operado_f76a34_idx'), models.Index(fields=['item', 'estado'], name='operaciones_item_id_515b6c_idx')],
            },
        ),
    ]
